### ISSUE TITLE
Missing parameters in Hall sensor models

### ISSUE THREAD

**Issue by christiankral** [AHaumer/BLDC#1]
When checking the examples some errors occured. In the examples the parameters `hallSensor.intervalTest[...].constantUpperLimit` and `hallSensor.intervalTest[...].constantLowerLimit` are not set. This seems to be a matter of default values of `BLDC.Sensors.HallSensor`.

**Comment by AHaumer** [comment]
Seems that you got an erroneous intermediate version, sorry. 
All examples are running now!
